import = [ 
    # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"

    # "~/.config/alacritty/one_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 3

decorations = "Buttonless"

opacity = 0.9 
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hasklug Nerd Font"

size = 16



