import = [ "~/.config/alacritty/tokyo-night.toml" ] 
[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 3

decorations = "Buttonless"

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hasklug Nerd Font"

size = 14
