import = [ 
    # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"

    # "~/.config/alacritty/one_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0

decorations = "Buttonless"

opacity = 1.0 
# blur = true

option_as_alt = "Both"

[font]
normal.family = "Hasklug Nerd Font"

size = 16


[shell]
program = "/bin/zsh"
args = ["-l"]



