format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$cmake$package$rust$nodejs$golang\ 
$aws$gcloud\
$cmd_duration$jobs$time\
$line_break\
$character"""

add_newline = true

[java]
format = '[$symbol($version)]($style) '
symbol = ' '

[aws]
format = '[$symbol($profile )(\($region\))]($style) '
symbol = '󰸏 '

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '
symbol = '󱇶 '

[cmake]
format = '[$symbol($version)]($style) '
symbol = '△ '

[rust]
format = '[$symbol($version)]($style) '
symbol = " "

[package]
format = '[ $version](208 bold) '

[golang]
format = '[$symbol($version)]($style) '
symbol = ' '

[nodejs]
format = "[$symbol($version)]($style) "

# [docker_context]
# format = '[$context](blue bold) '

[fill]
symbol = " "

[directory]
style = "blue"
read_only = ""
truncation_length = 4
truncate_to_repo = false
truncation_symbol = '.../'

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](purple)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
min_time = 1


[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"
